name: DevOps CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devops-lab-app ./app

      - name: Check Kubernetes Files
        run: |
          test -f k8s/deployment.yml
          test -f k8s/service.yml
          echo "Kubernetes YAML files are present"

      - name: Pipeline Completed
        run: echo "Docker build and Kubernetes file checks completed successfully"
